name: dhristisar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - geopandas
  - rasterio
  - streamlit
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - diffusers
      - ultralytics
